---
# vars file for tomcat9

tomcat_link: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.60/bin/apache-tomcat-9.0.60.tar.gz

tomcat_pkg: apache-tomcat-9.0.60.tar.gz

users_xml: ansible_roles/tomcat9/files/tomcat-users.xml

conf_link: /opt/tomcat/apache-tomcat-9.0.60/conf

#port: "8080"

#proto: "tcp"

#zone: "public"
